development:
  sessions:
    default:
      database: workreport
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: workreport
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>